version: '3.7'
services:
  ejabberd:
    image: ejabberd/ecs
    ports:
      - '5222:5222'
      - '5269:5269'
      - '5280:5280'
  app:
    container_name: react-chat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    depends_on:
      - 'ejabberd'
    environment:
      - NODE_ENV=development